"""AUTO-GENERATED by funova_screen_run_helpers.submit_runs(). Do not edit by hand."""
import os, sys
sys.path.insert(1, os.getenv("NOVA_HOME"))

from NOVA.manuscript.manuscript_figures_data_config_FuNOVA_Screen import (
    FuNOVA_Screen_BaseFigureConfig,
    FUNOVA_SCREEN_MARKERS,
    FUNOVA_SCREEN_BATCHES,
    FUNOVA_SCREEN_CELL_LINES,
    FUNOVA_SCREEN_ALL_CONDITIONS,
    FUNOVA_SCREEN_CONDITIONS_PLATES,
    FUNOVA_SCREEN_CONTROL_CONDITIONS_PLATES,
    FUNOVA_SCREEN_KDS_CONDITIONS_PLATES
)


class FuNOVA_Screen_Data_plate1_AllCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNB1', 'CTNNBL1', 'CYP46A1', 'DDHD1', 'DLD', 'ETV5', 'FAM149B1', 'FAM171A1', 'FBXO10', 'FGD1', 'FNBP1L', 'FOXK1', 'GABRA2', 'GAK', 'GHITM', 'GNB1L', 'GNG4', 'GRAMD4', 'HDAC2', 'BANP', 'HNRNPU', 'INPP5F', 'INTS8', 'IQSEC2', 'KIF3B', 'KIFAP3', 'LDLR', 'LRIF1', 'LRP1B', 'BOLA3', 'MAP3K4', 'MAP4', 'MBTPS1', 'MED15', 'MXRA8', 'NAE1', 'NAV1', 'NEIL1', 'BRD9', 'NFASC', 'NRP1', 'NUDCD3', 'non-targeting-00004-00017-p1', 'non-targeting-00010-00031-p1', 'non-targeting-00035-00050-p1', 'non-targeting-00053-00059-p1', 'non-targeting-00111-00121-p1', 'Empty-p1']


class FuNOVA_Screen_Data_plate2_AllCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NUP133', 'OGFOD1', 'PAK1', 'PAQR7', 'PDLIM4', 'PDZRN3', 'PHF2', 'CASD1', 'POLR3E', 'POMGNT2', 'PRIM1', 'RBBP6', 'RECK', 'RNF20', 'RUSC2', 'SEH1L', 'SENP5', 'CC2D2A', 'SMC1A', 'SNX30', 'STMN2', 'SYT16', 'TAF1', 'TBCD', 'TBCE', 'TELO2', 'TIMM21', 'TMEM50B', 'TMOD1', 'TMX2', 'TUBA1A', 'UROS', 'COPS8', 'ZBTB18', 'ZNF462', 'CTNNA2', 'CCDC152', 'CCDC183', 'CDH20', 'CDK7', 'CEP57L1', 'CHMP7', 'non-targeting-00004-00017-p2', 'non-targeting-00010-00031-p2', 'non-targeting-00035-00050-p2', 'non-targeting-00053-00059-p2', 'non-targeting-00111-00121-p2', 'Empty-p2']


class FuNOVA_Screen_Data_plate3_AllCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CSNK1E', 'DCX', 'ANXA11', 'DHX37', 'DLG5', 'DLGAP1', 'DLGAP2', 'DOC2A', 'DPY19L4', 'EFCAB2', 'GADD45A', 'ASRGL1', 'GNAL', 'GPCPD1', 'GRM2', 'MCM7', 'ATF7IP', 'MNAT1', 'MTMR3', 'MYCN', 'NADSYN1', 'NCDN', 'NECAB3', 'NME3', 'NOMO2', 'OSBP2', 'POLI', 'TDP-43-p3', 'Ranbp17-p3', 'PSD', 'RHBDD1', 'PTGIS', 'RPL29', 'RYR3', 'SEMA6C', 'SGF29', 'SLC39A9', 'SRR', 'BSN', 'SYN3', 'TCF4', 'TENM1', 'non-targeting-00004-00017-p3', 'non-targeting-00010-00031-p3', 'non-targeting-00035-00050-p3', 'non-targeting-00053-00059-p3', 'non-targeting-00111-00121-p3', 'Empty-p3']


class FuNOVA_Screen_Data_plate4_AllCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TFB1M', 'THSD7A', 'THY1', 'TMEM30A', 'WDR86', 'ZNF566', 'ZNF652', 'CAPRIN2', 'CCDC146', 'AKT3', 'ZNF772', 'AKIRIN2', 'CDK12', 'FAM193B', 'INVS', 'MAPKAP1', 'MYO1C', 'POLD1', 'RCOR2', 'SOBP', 'TDP1', 'TRRAP', 'USP24', 'ATF7IP2', 'BMP2K', 'CACNA2D2', 'CHMP2B', 'CYP51A1', 'ERO1B', 'HIVEP2', 'HSP90AB1', 'HSPH1', 'INPP5B', 'KDM1B', 'KIAA0232', 'NECAB2', 'ONECUT2', 'PIGZ', 'HMGCS1', 'PIK3C3', 'Ranbp17-p4', 'TDP-43-p4', 'non-targeting-00004-00017-p4', 'non-targeting-00010-00031-p4', 'non-targeting-00035-00050-p4', 'non-targeting-00053-00059-p4', 'non-targeting-00111-00121-p4', 'Empty-p4']


class FuNOVA_Screen_Data_plate1_ControlCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p1', 'non-targeting-00010-00031-p1', 'non-targeting-00035-00050-p1', 'non-targeting-00053-00059-p1', 'non-targeting-00111-00121-p1', 'Empty-p1']


class FuNOVA_Screen_Data_plate2_ControlCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p2', 'non-targeting-00010-00031-p2', 'non-targeting-00035-00050-p2', 'non-targeting-00053-00059-p2', 'non-targeting-00111-00121-p2', 'Empty-p2']


class FuNOVA_Screen_Data_plate3_ControlCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p3', 'non-targeting-00010-00031-p3', 'non-targeting-00035-00050-p3', 'non-targeting-00053-00059-p3', 'non-targeting-00111-00121-p3', 'Empty-p3']


class FuNOVA_Screen_Data_plate4_ControlCond(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p4', 'non-targeting-00010-00031-p4', 'non-targeting-00035-00050-p4', 'non-targeting-00053-00059-p4', 'non-targeting-00111-00121-p4', 'Empty-p4']


class FuNOVA_Screen_Data_AllCond_AllMarkers(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        pass


class FuNOVA_Screen_Data_AllCond_woDAPI(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.MARKERS_TO_EXCLUDE = ['HDGFL2', 'FK-2', 'DAPI']


class FuNOVA_Screen_Data_AllData_ByReps(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        pass


class FuNOVA_Screen_Data_AllData_ByBatches(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        pass


class FuNOVA_Screen_Data_plate1_BinaryCtrlKD_kd0_10(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p1', 'non-targeting-00010-00031-p1', 'non-targeting-00035-00050-p1', 'non-targeting-00053-00059-p1', 'non-targeting-00111-00121-p1', 'CTNNB1', 'CTNNBL1', 'CYP46A1', 'DDHD1', 'DLD', 'ETV5', 'FAM149B1', 'FAM171A1', 'FBXO10', 'FGD1']


class FuNOVA_Screen_Data_plate2_BinaryCtrlKD_kd0_10(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p2', 'non-targeting-00010-00031-p2', 'non-targeting-00035-00050-p2', 'non-targeting-00053-00059-p2', 'non-targeting-00111-00121-p2', 'NUP133', 'OGFOD1', 'PAK1', 'PAQR7', 'PDLIM4', 'PDZRN3', 'PHF2', 'CASD1', 'POLR3E', 'POMGNT2']


class FuNOVA_Screen_Data_plate3_BinaryCtrlKD_kd0_10(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p3', 'non-targeting-00010-00031-p3', 'non-targeting-00035-00050-p3', 'non-targeting-00053-00059-p3', 'non-targeting-00111-00121-p3', 'CSNK1E', 'DCX', 'ANXA11', 'DHX37', 'DLG5', 'DLGAP1', 'DLGAP2', 'DOC2A', 'DPY19L4', 'EFCAB2']


class FuNOVA_Screen_Data_plate4_BinaryCtrlKD_kd0_10(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['non-targeting-00004-00017-p4', 'non-targeting-00010-00031-p4', 'non-targeting-00035-00050-p4', 'non-targeting-00053-00059-p4', 'non-targeting-00111-00121-p4', 'TFB1M', 'THSD7A', 'THY1', 'TMEM30A', 'WDR86', 'ZNF566', 'ZNF652', 'CAPRIN2', 'CCDC146', 'AKT3']


class FuNOVA_Screen_Data_plate1_BinaryCtrlKD(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNB1', 'CTNNBL1', 'CYP46A1', 'DDHD1', 'DLD', 'ETV5', 'FAM149B1', 'FAM171A1', 'FBXO10', 'FGD1', 'FNBP1L', 'FOXK1', 'GABRA2', 'GAK', 'GHITM', 'GNB1L', 'GNG4', 'GRAMD4', 'HDAC2', 'BANP', 'HNRNPU', 'INPP5F', 'INTS8', 'IQSEC2', 'KIF3B', 'KIFAP3', 'LDLR', 'LRIF1', 'LRP1B', 'BOLA3', 'MAP3K4', 'MAP4', 'MBTPS1', 'MED15', 'MXRA8', 'NAE1', 'NAV1', 'NEIL1', 'BRD9', 'NFASC', 'NRP1', 'NUDCD3', 'non-targeting-00004-00017-p1', 'non-targeting-00010-00031-p1', 'non-targeting-00035-00050-p1', 'non-targeting-00053-00059-p1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate2_BinaryCtrlKD(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NUP133', 'OGFOD1', 'PAK1', 'PAQR7', 'PDLIM4', 'PDZRN3', 'PHF2', 'CASD1', 'POLR3E', 'POMGNT2', 'PRIM1', 'RBBP6', 'RECK', 'RNF20', 'RUSC2', 'SEH1L', 'SENP5', 'CC2D2A', 'SMC1A', 'SNX30', 'STMN2', 'SYT16', 'TAF1', 'TBCD', 'TBCE', 'TELO2', 'TIMM21', 'TMEM50B', 'TMOD1', 'TMX2', 'TUBA1A', 'UROS', 'COPS8', 'ZBTB18', 'ZNF462', 'CTNNA2', 'CCDC152', 'CCDC183', 'CDH20', 'CDK7', 'CEP57L1', 'CHMP7', 'non-targeting-00004-00017-p2', 'non-targeting-00010-00031-p2', 'non-targeting-00035-00050-p2', 'non-targeting-00053-00059-p2', 'non-targeting-00111-00121-p2']


class FuNOVA_Screen_Data_plate3_BinaryCtrlKD(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CSNK1E', 'DCX', 'ANXA11', 'DHX37', 'DLG5', 'DLGAP1', 'DLGAP2', 'DOC2A', 'DPY19L4', 'EFCAB2', 'GADD45A', 'ASRGL1', 'GNAL', 'GPCPD1', 'GRM2', 'MCM7', 'ATF7IP', 'MNAT1', 'MTMR3', 'MYCN', 'NADSYN1', 'NCDN', 'NECAB3', 'NME3', 'NOMO2', 'OSBP2', 'POLI', 'TDP-43-p3', 'Ranbp17-p3', 'PSD', 'RHBDD1', 'PTGIS', 'RPL29', 'RYR3', 'SEMA6C', 'SGF29', 'SLC39A9', 'SRR', 'BSN', 'SYN3', 'TCF4', 'TENM1', 'non-targeting-00004-00017-p3', 'non-targeting-00010-00031-p3', 'non-targeting-00035-00050-p3', 'non-targeting-00053-00059-p3', 'non-targeting-00111-00121-p3']


class FuNOVA_Screen_Data_plate4_BinaryCtrlKD(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TFB1M', 'THSD7A', 'THY1', 'TMEM30A', 'WDR86', 'ZNF566', 'ZNF652', 'CAPRIN2', 'CCDC146', 'AKT3', 'ZNF772', 'AKIRIN2', 'CDK12', 'FAM193B', 'INVS', 'MAPKAP1', 'MYO1C', 'POLD1', 'RCOR2', 'SOBP', 'TDP1', 'TRRAP', 'USP24', 'ATF7IP2', 'BMP2K', 'CACNA2D2', 'CHMP2B', 'CYP51A1', 'ERO1B', 'HIVEP2', 'HSP90AB1', 'HSPH1', 'INPP5B', 'KDM1B', 'KIAA0232', 'NECAB2', 'ONECUT2', 'PIGZ', 'HMGCS1', 'PIK3C3', 'Ranbp17-p4', 'TDP-43-p4', 'non-targeting-00004-00017-p4', 'non-targeting-00010-00031-p4', 'non-targeting-00035-00050-p4', 'non-targeting-00053-00059-p4', 'non-targeting-00111-00121-p4']


class FuNOVA_Screen_Data_plate1_CTNNB1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNB1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_CTNNB1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNB1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_CTNNB1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNB1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_CTNNB1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNB1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_CTNNB1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNB1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_CTNNBL1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNBL1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_CTNNBL1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNBL1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_CTNNBL1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNBL1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_CTNNBL1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNBL1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_CTNNBL1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CTNNBL1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_CYP46A1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CYP46A1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_CYP46A1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CYP46A1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_CYP46A1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CYP46A1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_CYP46A1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CYP46A1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_CYP46A1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CYP46A1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_DDHD1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DDHD1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_DDHD1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DDHD1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_DDHD1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DDHD1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_DDHD1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DDHD1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_DDHD1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DDHD1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_DLD_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DLD', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_DLD_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DLD', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_DLD_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DLD', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_DLD_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DLD', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_DLD_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DLD', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_ETV5_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['ETV5', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_ETV5_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['ETV5', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_ETV5_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['ETV5', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_ETV5_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['ETV5', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_ETV5_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['ETV5', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_FAM149B1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM149B1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_FAM149B1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM149B1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_FAM149B1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM149B1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_FAM149B1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM149B1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_FAM149B1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM149B1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_FAM171A1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM171A1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_FAM171A1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM171A1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_FAM171A1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM171A1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_FAM171A1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM171A1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_FAM171A1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FAM171A1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_FBXO10_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FBXO10', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_FBXO10_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FBXO10', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_FBXO10_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FBXO10', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_FBXO10_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FBXO10', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_FBXO10_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FBXO10', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_FGD1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FGD1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_FGD1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FGD1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_FGD1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FGD1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_FGD1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FGD1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_FGD1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FGD1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_FNBP1L_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FNBP1L', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_FNBP1L_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FNBP1L', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_FNBP1L_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FNBP1L', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_FNBP1L_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FNBP1L', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_FNBP1L_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FNBP1L', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_FOXK1_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FOXK1', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_FOXK1_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FOXK1', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_FOXK1_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FOXK1', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_FOXK1_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FOXK1', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_FOXK1_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['FOXK1', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_GAK_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GAK', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_GAK_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GAK', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_GAK_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GAK', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_GAK_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GAK', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_GAK_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GAK', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_GNB1L_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNB1L', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_GNB1L_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNB1L', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_GNB1L_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNB1L', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_GNB1L_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNB1L', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_GNB1L_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNB1L', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_plate1_LDLR_vs_non_targeting_00004_00017_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['LDLR', 'non-targeting-00004-00017-p1']


class FuNOVA_Screen_Data_plate1_LDLR_vs_non_targeting_00010_00031_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['LDLR', 'non-targeting-00010-00031-p1']


class FuNOVA_Screen_Data_plate1_LDLR_vs_non_targeting_00035_00050_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['LDLR', 'non-targeting-00035-00050-p1']


class FuNOVA_Screen_Data_plate1_LDLR_vs_non_targeting_00053_00059_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['LDLR', 'non-targeting-00053-00059-p1']


class FuNOVA_Screen_Data_plate1_LDLR_vs_non_targeting_00111_00121_p1(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['LDLR', 'non-targeting-00111-00121-p1']


class FuNOVA_Screen_Data_AllCond_HighlightHits(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        pass


class FuNOVA_Screen_Data_plate2_NUP133_vs_non_targeting_00004_00017_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NUP133', 'non-targeting-00004-00017-p2']


class FuNOVA_Screen_Data_plate2_NUP133_vs_non_targeting_00010_00031_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NUP133', 'non-targeting-00010-00031-p2']


class FuNOVA_Screen_Data_plate2_NUP133_vs_non_targeting_00035_00050_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NUP133', 'non-targeting-00035-00050-p2']


class FuNOVA_Screen_Data_plate2_NUP133_vs_non_targeting_00053_00059_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NUP133', 'non-targeting-00053-00059-p2']


class FuNOVA_Screen_Data_plate2_NUP133_vs_non_targeting_00111_00121_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NUP133', 'non-targeting-00111-00121-p2']


class FuNOVA_Screen_Data_plate2_SYT16_vs_non_targeting_00004_00017_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['SYT16', 'non-targeting-00004-00017-p2']


class FuNOVA_Screen_Data_plate2_SYT16_vs_non_targeting_00010_00031_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['SYT16', 'non-targeting-00010-00031-p2']


class FuNOVA_Screen_Data_plate2_SYT16_vs_non_targeting_00035_00050_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['SYT16', 'non-targeting-00035-00050-p2']


class FuNOVA_Screen_Data_plate2_SYT16_vs_non_targeting_00053_00059_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['SYT16', 'non-targeting-00053-00059-p2']


class FuNOVA_Screen_Data_plate2_SYT16_vs_non_targeting_00111_00121_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['SYT16', 'non-targeting-00111-00121-p2']


class FuNOVA_Screen_Data_plate2_TBCE_vs_non_targeting_00004_00017_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TBCE', 'non-targeting-00004-00017-p2']


class FuNOVA_Screen_Data_plate2_TBCE_vs_non_targeting_00010_00031_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TBCE', 'non-targeting-00010-00031-p2']


class FuNOVA_Screen_Data_plate2_TBCE_vs_non_targeting_00035_00050_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TBCE', 'non-targeting-00035-00050-p2']


class FuNOVA_Screen_Data_plate2_TBCE_vs_non_targeting_00053_00059_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TBCE', 'non-targeting-00053-00059-p2']


class FuNOVA_Screen_Data_plate2_TBCE_vs_non_targeting_00111_00121_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TBCE', 'non-targeting-00111-00121-p2']


class FuNOVA_Screen_Data_plate2_TELO2_vs_non_targeting_00004_00017_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TELO2', 'non-targeting-00004-00017-p2']


class FuNOVA_Screen_Data_plate2_TELO2_vs_non_targeting_00010_00031_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TELO2', 'non-targeting-00010-00031-p2']


class FuNOVA_Screen_Data_plate2_TELO2_vs_non_targeting_00035_00050_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TELO2', 'non-targeting-00035-00050-p2']


class FuNOVA_Screen_Data_plate2_TELO2_vs_non_targeting_00053_00059_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TELO2', 'non-targeting-00053-00059-p2']


class FuNOVA_Screen_Data_plate2_TELO2_vs_non_targeting_00111_00121_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TELO2', 'non-targeting-00111-00121-p2']


class FuNOVA_Screen_Data_plate2_TMEM50B_vs_non_targeting_00004_00017_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TMEM50B', 'non-targeting-00004-00017-p2']


class FuNOVA_Screen_Data_plate2_TMEM50B_vs_non_targeting_00010_00031_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TMEM50B', 'non-targeting-00010-00031-p2']


class FuNOVA_Screen_Data_plate2_TMEM50B_vs_non_targeting_00035_00050_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TMEM50B', 'non-targeting-00035-00050-p2']


class FuNOVA_Screen_Data_plate2_TMEM50B_vs_non_targeting_00053_00059_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TMEM50B', 'non-targeting-00053-00059-p2']


class FuNOVA_Screen_Data_plate2_TMEM50B_vs_non_targeting_00111_00121_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TMEM50B', 'non-targeting-00111-00121-p2']


class FuNOVA_Screen_Data_plate2_POLR3E_vs_non_targeting_00004_00017_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLR3E', 'non-targeting-00004-00017-p2']


class FuNOVA_Screen_Data_plate2_POLR3E_vs_non_targeting_00010_00031_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLR3E', 'non-targeting-00010-00031-p2']


class FuNOVA_Screen_Data_plate2_POLR3E_vs_non_targeting_00035_00050_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLR3E', 'non-targeting-00035-00050-p2']


class FuNOVA_Screen_Data_plate2_POLR3E_vs_non_targeting_00053_00059_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLR3E', 'non-targeting-00053-00059-p2']


class FuNOVA_Screen_Data_plate2_POLR3E_vs_non_targeting_00111_00121_p2(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLR3E', 'non-targeting-00111-00121-p2']


class FuNOVA_Screen_Data_plate4_RCOR2_vs_non_targeting_00004_00017_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['RCOR2', 'non-targeting-00004-00017-p4']


class FuNOVA_Screen_Data_plate4_RCOR2_vs_non_targeting_00010_00031_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['RCOR2', 'non-targeting-00010-00031-p4']


class FuNOVA_Screen_Data_plate4_RCOR2_vs_non_targeting_00035_00050_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['RCOR2', 'non-targeting-00035-00050-p4']


class FuNOVA_Screen_Data_plate4_RCOR2_vs_non_targeting_00053_00059_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['RCOR2', 'non-targeting-00053-00059-p4']


class FuNOVA_Screen_Data_plate4_RCOR2_vs_non_targeting_00111_00121_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['RCOR2', 'non-targeting-00111-00121-p4']


class FuNOVA_Screen_Data_plate4_TDP1_vs_non_targeting_00004_00017_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TDP1', 'non-targeting-00004-00017-p4']


class FuNOVA_Screen_Data_plate4_TDP1_vs_non_targeting_00010_00031_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TDP1', 'non-targeting-00010-00031-p4']


class FuNOVA_Screen_Data_plate4_TDP1_vs_non_targeting_00035_00050_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TDP1', 'non-targeting-00035-00050-p4']


class FuNOVA_Screen_Data_plate4_TDP1_vs_non_targeting_00053_00059_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TDP1', 'non-targeting-00053-00059-p4']


class FuNOVA_Screen_Data_plate4_TDP1_vs_non_targeting_00111_00121_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['TDP1', 'non-targeting-00111-00121-p4']


class FuNOVA_Screen_Data_plate4_BMP2K_vs_non_targeting_00004_00017_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['BMP2K', 'non-targeting-00004-00017-p4']


class FuNOVA_Screen_Data_plate4_BMP2K_vs_non_targeting_00010_00031_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['BMP2K', 'non-targeting-00010-00031-p4']


class FuNOVA_Screen_Data_plate4_BMP2K_vs_non_targeting_00035_00050_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['BMP2K', 'non-targeting-00035-00050-p4']


class FuNOVA_Screen_Data_plate4_BMP2K_vs_non_targeting_00053_00059_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['BMP2K', 'non-targeting-00053-00059-p4']


class FuNOVA_Screen_Data_plate4_BMP2K_vs_non_targeting_00111_00121_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['BMP2K', 'non-targeting-00111-00121-p4']


class FuNOVA_Screen_Data_plate4_CACNA2D2_vs_non_targeting_00004_00017_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CACNA2D2', 'non-targeting-00004-00017-p4']


class FuNOVA_Screen_Data_plate4_CACNA2D2_vs_non_targeting_00010_00031_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CACNA2D2', 'non-targeting-00010-00031-p4']


class FuNOVA_Screen_Data_plate4_CACNA2D2_vs_non_targeting_00035_00050_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CACNA2D2', 'non-targeting-00035-00050-p4']


class FuNOVA_Screen_Data_plate4_CACNA2D2_vs_non_targeting_00053_00059_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CACNA2D2', 'non-targeting-00053-00059-p4']


class FuNOVA_Screen_Data_plate4_CACNA2D2_vs_non_targeting_00111_00121_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CACNA2D2', 'non-targeting-00111-00121-p4']


class FuNOVA_Screen_Data_plate4_KIAA0232_vs_non_targeting_00004_00017_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['KIAA0232', 'non-targeting-00004-00017-p4']


class FuNOVA_Screen_Data_plate4_KIAA0232_vs_non_targeting_00010_00031_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['KIAA0232', 'non-targeting-00010-00031-p4']


class FuNOVA_Screen_Data_plate4_KIAA0232_vs_non_targeting_00035_00050_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['KIAA0232', 'non-targeting-00035-00050-p4']


class FuNOVA_Screen_Data_plate4_KIAA0232_vs_non_targeting_00053_00059_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['KIAA0232', 'non-targeting-00053-00059-p4']


class FuNOVA_Screen_Data_plate4_KIAA0232_vs_non_targeting_00111_00121_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['KIAA0232', 'non-targeting-00111-00121-p4']


class FuNOVA_Screen_Data_plate4_HMGCS1_vs_non_targeting_00004_00017_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['HMGCS1', 'non-targeting-00004-00017-p4']


class FuNOVA_Screen_Data_plate4_HMGCS1_vs_non_targeting_00010_00031_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['HMGCS1', 'non-targeting-00010-00031-p4']


class FuNOVA_Screen_Data_plate4_HMGCS1_vs_non_targeting_00035_00050_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['HMGCS1', 'non-targeting-00035-00050-p4']


class FuNOVA_Screen_Data_plate4_HMGCS1_vs_non_targeting_00053_00059_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['HMGCS1', 'non-targeting-00053-00059-p4']


class FuNOVA_Screen_Data_plate4_HMGCS1_vs_non_targeting_00111_00121_p4(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['HMGCS1', 'non-targeting-00111-00121-p4']


class FuNOVA_Screen_Data_plate3_CSNK1E_vs_non_targeting_00004_00017_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CSNK1E', 'non-targeting-00004-00017-p3']


class FuNOVA_Screen_Data_plate3_CSNK1E_vs_non_targeting_00010_00031_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CSNK1E', 'non-targeting-00010-00031-p3']


class FuNOVA_Screen_Data_plate3_CSNK1E_vs_non_targeting_00035_00050_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CSNK1E', 'non-targeting-00035-00050-p3']


class FuNOVA_Screen_Data_plate3_CSNK1E_vs_non_targeting_00053_00059_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CSNK1E', 'non-targeting-00053-00059-p3']


class FuNOVA_Screen_Data_plate3_CSNK1E_vs_non_targeting_00111_00121_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['CSNK1E', 'non-targeting-00111-00121-p3']


class FuNOVA_Screen_Data_plate3_DCX_vs_non_targeting_00004_00017_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DCX', 'non-targeting-00004-00017-p3']


class FuNOVA_Screen_Data_plate3_DCX_vs_non_targeting_00010_00031_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DCX', 'non-targeting-00010-00031-p3']


class FuNOVA_Screen_Data_plate3_DCX_vs_non_targeting_00035_00050_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DCX', 'non-targeting-00035-00050-p3']


class FuNOVA_Screen_Data_plate3_DCX_vs_non_targeting_00053_00059_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DCX', 'non-targeting-00053-00059-p3']


class FuNOVA_Screen_Data_plate3_DCX_vs_non_targeting_00111_00121_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['DCX', 'non-targeting-00111-00121-p3']


class FuNOVA_Screen_Data_plate3_GNAL_vs_non_targeting_00004_00017_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNAL', 'non-targeting-00004-00017-p3']


class FuNOVA_Screen_Data_plate3_GNAL_vs_non_targeting_00010_00031_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNAL', 'non-targeting-00010-00031-p3']


class FuNOVA_Screen_Data_plate3_GNAL_vs_non_targeting_00035_00050_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNAL', 'non-targeting-00035-00050-p3']


class FuNOVA_Screen_Data_plate3_GNAL_vs_non_targeting_00053_00059_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNAL', 'non-targeting-00053-00059-p3']


class FuNOVA_Screen_Data_plate3_GNAL_vs_non_targeting_00111_00121_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['GNAL', 'non-targeting-00111-00121-p3']


class FuNOVA_Screen_Data_plate3_MYCN_vs_non_targeting_00004_00017_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['MYCN', 'non-targeting-00004-00017-p3']


class FuNOVA_Screen_Data_plate3_MYCN_vs_non_targeting_00010_00031_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['MYCN', 'non-targeting-00010-00031-p3']


class FuNOVA_Screen_Data_plate3_MYCN_vs_non_targeting_00035_00050_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['MYCN', 'non-targeting-00035-00050-p3']


class FuNOVA_Screen_Data_plate3_MYCN_vs_non_targeting_00053_00059_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['MYCN', 'non-targeting-00053-00059-p3']


class FuNOVA_Screen_Data_plate3_MYCN_vs_non_targeting_00111_00121_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['MYCN', 'non-targeting-00111-00121-p3']


class FuNOVA_Screen_Data_plate3_NADSYN1_vs_non_targeting_00004_00017_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NADSYN1', 'non-targeting-00004-00017-p3']


class FuNOVA_Screen_Data_plate3_NADSYN1_vs_non_targeting_00010_00031_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NADSYN1', 'non-targeting-00010-00031-p3']


class FuNOVA_Screen_Data_plate3_NADSYN1_vs_non_targeting_00035_00050_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NADSYN1', 'non-targeting-00035-00050-p3']


class FuNOVA_Screen_Data_plate3_NADSYN1_vs_non_targeting_00053_00059_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NADSYN1', 'non-targeting-00053-00059-p3']


class FuNOVA_Screen_Data_plate3_NADSYN1_vs_non_targeting_00111_00121_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['NADSYN1', 'non-targeting-00111-00121-p3']


class FuNOVA_Screen_Data_plate3_POLI_vs_non_targeting_00004_00017_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLI', 'non-targeting-00004-00017-p3']


class FuNOVA_Screen_Data_plate3_POLI_vs_non_targeting_00010_00031_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLI', 'non-targeting-00010-00031-p3']


class FuNOVA_Screen_Data_plate3_POLI_vs_non_targeting_00035_00050_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLI', 'non-targeting-00035-00050-p3']


class FuNOVA_Screen_Data_plate3_POLI_vs_non_targeting_00053_00059_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLI', 'non-targeting-00053-00059-p3']


class FuNOVA_Screen_Data_plate3_POLI_vs_non_targeting_00111_00121_p3(FuNOVA_Screen_BaseFigureConfig):
    def __init__(self):
        super().__init__()
        self.CONDITIONS = ['POLI', 'non-targeting-00111-00121-p3']
