# python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelA > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelA_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelB > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelB_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelC > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelC_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelD > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelD_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelE > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelE_150725.log
# python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelF > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelF_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelG > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelG_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelH > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelH_150725.log
# python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelI > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelI_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelJ > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelJ_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelK > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelK_150725.log
python /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne150725/ConfigPanelL > /home/projects/hornsteinlab/Collaboration/MOmaps_Sagy/NOVA/tools/images_organizer/AlyssaCoyne/logs/Coyne150725/panelL_150725.log