# python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelA > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelA_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelB > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelB_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelC > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelC_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelD > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelD_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelE > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelE_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelF > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelF_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelG > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelG_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelH > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelH_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelI > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelI_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelJ > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelJ_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelK > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelK_110525.log
python /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/main.py ./tools/images_organizer/AlyssaCoyne/configCoyne080525/ConfigPanelL > /home/projects/hornsteinlab/Collaboration/MOmaps/tools/images_organizer/AlyssaCoyne/logs/Coyne080525/panelL_110525.log