./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_A -a ./tools/images_organizer/opera_version/config_A/Config_A -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_B -a ./tools/images_organizer/opera_version/config_B/Config_B -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_C -a ./tools/images_organizer/opera_version/config_C/Config_C -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_D -a ./tools/images_organizer/opera_version/config_D/Config_D -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_E -a ./tools/images_organizer/opera_version/config_E/Config_E -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_F -a ./tools/images_organizer/opera_version/config_F/Config_F -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_G -a ./tools/images_organizer/opera_version/config_G/Config_G -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_H -a ./tools/images_organizer/opera_version/config_H/Config_H -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_I -a ./tools/images_organizer/opera_version/config_I/Config_I -q new-short
./bash_commands/run_py.sh ./tools/images_organizer/opera_version/main -m 10000 -j organize_opera_J -a ./tools/images_organizer/opera_version/config_J/Config_J -q new-short